name: Weekly Build and Test

on:
  push:
    branches:
      - 1.8.1-EOL
  schedule:
    - cron: "0 0 */7 * *"
    
    
jobs:
  build-linux:
    runs-on: ubuntu-latest   
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: '3.8.13'
    - run:   |
         sudo apt update
         sudo apt install gcc-10 g++-10
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Initiate conda channels
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: testenv
        python-version: 3.8.13
        channels: conda-forge,bioconda
        allow-softlinks: true
        channel-priority: flexible
        show-channel-urls: true
        use-only-tar-bz2: true
          
    - name: Set up environment
      run: |
        wget https://data.qiime2.org/distro/core/qiime2-2022.8-py38-linux-conda.yml
        conda env create -n qiime2-2022.8 --file qiime2-2022.8-py38-linux-conda.yml
    - name: Install Dependencies
      run: |
        source activate qiime2-2022.8
        conda install -y -c bioconda bbmap==38.69
        pip install itsxpress==1.8.1
        conda install biopython
        pip install pyzstd
        pip install pytest
        pip install .
    - name: Test with pytest
      run: |
        source activate qiime2-2022.8
        pytest
